### ISSUE TITLE
NoMethodError: undefined method `comment' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn>

### ISSUE THREAD

**Issue by nirname** [koedame/rails-mermaid_erd#78]
While running
```
rake mermaid_erd
```
I face the following issue
```
NoMethodError: undefined method `comment' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x000055d5602cb3a8>
```

<details>

```
Called from /usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:238:in `block in load_dependency'
-- foreign_keys("delayed_jobs")
   -> 0.0020s
rake aborted!
NoMethodError: undefined method `comment' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x0000563d69c1a370>
/usr/local/bundle/gems/rails-mermaid_erd-0.1.2/lib/rails-mermaid_erd.rb:43:in `block (3 levels) in <module:RailsMermaidErd>'
/usr/local/bundle/gems/rails-mermaid_erd-0.1.2/lib/rails-mermaid_erd.rb:32:in `each'
/usr/local/bundle/gems/rails-mermaid_erd-0.1.2/lib/rails-mermaid_erd.rb:32:in `block (2 levels) in <module:RailsMermaidErd>'
/usr/local/bundle/gems/rails-mermaid_erd-0.1.2/lib/rails-mermaid_erd.rb:18:in `each'
/usr/local/bundle/gems/rails-mermaid_erd-0.1.2/lib/rails-mermaid_erd.rb:18:in `block in <module:RailsMermaidErd>'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<top (required)>'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/usr/local/bundle/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
```

</details>

Rails 4.2
Using rails-mermaid_erd 0.1.2

I know that 4.2. is not maintained anymore, but in case older versions of Rails are not supported there probably should be a dependency.

**Comment by unchidev** [comment]
Thanks for the report, and apologies for the very late reply.

The root cause is that `ActiveRecord::ConnectionAdapters::PostgreSQLColumn#comment` was introduced in Rails 5.0, so it does not exist on Rails 4.2.

Since v0.2.0 the gemspec declares `spec.add_dependency "rails", ">= 5.2"`, so Bundler will no longer resolve `rails-mermaid_erd` on Rails 4.2 — the exact dependency guard you suggested. The current release (v0.6.0) is unaffected because every supported Rails version (5.2+) provides `column.comment`.

Closing as resolved by the version constraint. Please reopen if you hit this on a supported Rails version.
